name:                haskellbook
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/jproyo/haskellbook#readme
license:             BSD3
author:              Juan Pablo Royo Sales
maintainer:          juanpablo.royo@gmail.com
copyright:           2018 Juan Pablo Royo Sales
category:            Excercise
extra-source-files:
- README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5
  - text


library:
  source-dirs: src


default-extensions:
  - OverloadedStrings

executables:
  haskellbook:
    source-dirs:
      - app
      - src
    main: Main.hs

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - src
      - test
    dependencies:
      - hspec == 2.*
      - QuickCheck
